In [5]:
import pandas as pd
from io import StringIO

Data = '''
[
  {
    "employee_name": "James",
    "email": "james@gmail.com",
    "job_profile": [
      {"title1": "Team Lead", "title2": "Sr.Software engineer"}
    ]
  }
]
'''

df = pd.read_json(StringIO(Data))
print(df)

  employee_name            email  \
0         James  james@gmail.com

                                         job_profile
0  [{'title1': 'Team Lead', 'title2': 'Sr.Softwar...

In [6]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"[{'title1': 'Team Lead', 'title2': 'Sr.Softwar..."

In [7]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":[{"title1":"Team Lead","title2":"Sr.Software engineer"}]}}'

In [8]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)

In [9]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [10]:
df.to_csv("wine.csv")

In [15]:
url="https://www.fdic.gov/bank/individual/failed/banklist.html"

df=pd.read_html(url)

In [14]:
%pip install lxml

Collecting lxml
  Downloading lxml-6.0.1-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Downloading lxml-6.0.1-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 1.4 MB/s eta 0:00:03
   ---------- ----------------------------- 1.0/4.0 MB 1.8 MB/s eta 0:00:02
   --------------- ------------------------ 1.6/4.0 MB 2.1 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 2.4 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 2.8 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.1
Note: you may need to restart the kernel to use updated packages.

In [16]:
url="https://www.fdic.gov/bank/individual/failed/banklist.html"

df=pd.read_html(url)

In [17]:
%pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\asus\downloads\python\venv\lib\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5lib

   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   ---------------------------------------- 2/2 [html5lib]

Successfully installed html5lib-1.1 webencodings-0.5.1
Note: you may need to restart the kernel to use updated packages.

In [18]:
%pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.13.5-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4)
  Downloading soupsieve-2.8-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\asus\downloads\python\venv\lib\site-packages (from beautifulsoup4) (4.15.0)
Downloading beautifulsoup4-4.13.5-py3-none-any.whl (105 kB)
Downloading soupsieve-2.8-py3-none-any.whl (36 kB)
Installing collected packages: soupsieve, beautifulsoup4

   ---------------------------------------- 0/2 [soupsieve]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   ---------------------------------------- 2/2 [beautifulsoup4]

Successfully installed beautifulsoup4-4.13.5 soupsieve-2.8
Note: you may need to restart the kernel to use updated packages.